<?php
require_once __DIR__ . '/env_loader.php';

// Accept either naming convention: STRIPE_PRICE_* (see .env.example) or the
// *_PRICE_ID names the live .env was actually set up with.
define('STRIPE_PRICE_STARTER',    env('STRIPE_PRICE_STARTER')    ?: env('STARTER_PRICE_ID'));
define('STRIPE_PRICE_GROWTH',     env('STRIPE_PRICE_GROWTH')     ?: env('GROWTH_PRICE_ID'));
define('STRIPE_PRICE_ENTERPRISE', env('STRIPE_PRICE_ENTERPRISE') ?: env('ENTERPRISE_PRICE_ID'));

define('PLAN_STARTER_CREDITS', (int)env('PLAN_STARTER_CREDITS', 1000));
define('PLAN_GROWTH_CREDITS', (int)env('PLAN_GROWTH_CREDITS', 6000));
define('PLAN_ENTERPRISE_CREDITS', (int)env('PLAN_ENTERPRISE_CREDITS', 17000));

define('PLAN_STARTER_PRICE', (int)env('PLAN_STARTER_PRICE', 95));
define('PLAN_GROWTH_PRICE', (int)env('PLAN_GROWTH_PRICE', 295));
define('PLAN_ENTERPRISE_PRICE', (int)env('PLAN_ENTERPRISE_PRICE', 495));

// One-time free credits granted at signup (free tier).
define('FREE_TIER_CREDITS', (int)env('FREE_TIER_CREDITS', 100));

$PLAN_CREDITS = [];
if (STRIPE_PRICE_STARTER) $PLAN_CREDITS[STRIPE_PRICE_STARTER] = PLAN_STARTER_CREDITS;
if (STRIPE_PRICE_GROWTH) $PLAN_CREDITS[STRIPE_PRICE_GROWTH] = PLAN_GROWTH_CREDITS;
if (STRIPE_PRICE_ENTERPRISE) $PLAN_CREDITS[STRIPE_PRICE_ENTERPRISE] = PLAN_ENTERPRISE_CREDITS;
