<?php
require_once __DIR__ . '/env_loader.php';

define('STRIPE_PRICE_STARTER', env('STRIPE_PRICE_STARTER'));
define('STRIPE_PRICE_GROWTH', env('STRIPE_PRICE_GROWTH'));
define('STRIPE_PRICE_ENTERPRISE', env('STRIPE_PRICE_ENTERPRISE'));

define('PLAN_STARTER_CREDITS', (int)env('PLAN_STARTER_CREDITS', 1000));
define('PLAN_GROWTH_CREDITS', (int)env('PLAN_GROWTH_CREDITS', 10000));
define('PLAN_ENTERPRISE_CREDITS', (int)env('PLAN_ENTERPRISE_CREDITS', 100000));

define('PLAN_STARTER_PRICE', (int)env('PLAN_STARTER_PRICE', 499));
define('PLAN_GROWTH_PRICE', (int)env('PLAN_GROWTH_PRICE', 999));
define('PLAN_ENTERPRISE_PRICE', (int)env('PLAN_ENTERPRISE_PRICE', 2999));

$PLAN_CREDITS = [];
if (STRIPE_PRICE_STARTER) $PLAN_CREDITS[STRIPE_PRICE_STARTER] = PLAN_STARTER_CREDITS;
if (STRIPE_PRICE_GROWTH) $PLAN_CREDITS[STRIPE_PRICE_GROWTH] = PLAN_GROWTH_CREDITS;
if (STRIPE_PRICE_ENTERPRISE) $PLAN_CREDITS[STRIPE_PRICE_ENTERPRISE] = PLAN_ENTERPRISE_CREDITS;
